# Generated by Django 5.2.6 on 2025-09-26 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
                ('paper', models.FileField(upload_to='papers/')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=50)),
                ('payed', models.BooleanField(default=False)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='conferenceApp.conference')),
            ],
        ),
    ]
