# Generated by Django 5.2.6 on 2025-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('theme', models.CharField(choices=[('IA', 'Computer science & IA'), ('SE', 'science & engineering'), ('SC', 'social science & education'), ('ID_Theme', 'Interdisciplinary Themes')], default='IA', max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('descripption', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
