# Generated by Django 5.2.6 on 2025-09-26 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_role', models.CharField(choices=[('chair', 'chair'), ('co-chair', 'co-chair'), ('member', 'memeber')], editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date_joined', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='conferenceApp.conference')),
            ],
        ),
    ]
