# Generated by Django 5.2.6 on 2025-10-10 10:13

import django.core.validators
import submissionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissionApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.TextField(validators=[submissionApp.models.validate_max_keywords]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
